task 7 completed
Glt1b/nc-games pull request #5
Opened 2022-11-16 09:00 UTC by Glt1b

2022-11-16 09:04 UTC, emilyb93 commented on __tests__/app.test.js
> +
We also need a test for when the user is provided but does not exist in the database

2022-11-16 09:11 UTC, emilyb93 commented on models/games_models.js
> +}};
A few notes here, we dont need to select from reviews to find out if it exists firsts. When we insert the comment with the review_id, this is a foreign key, if they key doesnt exist to make a link in the other table, SQL will throw an error and we can then handle that error.

Also, we dont need to give the created_at and votes fields, these will be added by SQL as they have DEFAULT properties in the seed function when we created the table.

Lastly, this is starting to look a lot like nested promises and i want us to move away from, please refactor so this is only in a single promise chain

2022-11-16 09:11 UTC, emilyb93 requested changes
Left a comment

2022-11-16 11:48 UTC, Harrison365 requested changes
Hey Marcin.
Please...
-Test for specific review_id (it may be worth testing the whole response rather then separately like you are doing now)
-Test for a username that doesn't exist (404)

Thanks :)

2022-11-17 09:30 UTC, Harrison365 requested changes
Hey Marcin :) 
Please...
-Test that the correct comment_id comes back 
-Add test for present user, missing body
-Add test for present username and body but the username doesn't exist.

Thanks :)

2022-11-17 09:34 UTC, emilyb93 approved these changes

2022-11-17 09:40 UTC, merged